services:
  hardhat:
    container_name: hardhat
    image: node:16
    working_dir: /home/node/app/ethereum/
    environment:
      - REPORT_GAS=TRUE
    volumes:
      - ./:/home/node/app
    ports:
      - "8545:8545"
    command: sh -c "npm install --verbose && npx hardhat node"

  react:
    container_name: react
    image: node:16
    working_dir: /home/node/app
    environment:
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "80:3000"
    command: sh -c "npm install --verbose && npm run start"
